sudo : required
services:
  -docker


before_install:
  - docker build -t javadah/core-api .
  - echo "&docker_pass" | docker login -u "$docker_id" --password-stdin
  - docker push javadah/core-api


  