version: "3"
services:
  core_api:
    image: core_api_v9
    ports:
      - 8002:8002
    links:
      - file
    networks:
      - frontend
  file:
      image: javadah/file_v2:latest
      ports:
        - "50052:50052"
      networks:
      - frontend

  
networks:
  frontend:
     
 
      

