// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package fileserv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type Auth struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Auth) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Auth) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type NoAuth struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoAuth) Reset()         { *m = NoAuth{} }
func (m *NoAuth) String() string { return proto.CompactTextString(m) }
func (*NoAuth) ProtoMessage()    {}
func (*NoAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *NoAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoAuth.Unmarshal(m, b)
}
func (m *NoAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoAuth.Marshal(b, m, deterministic)
}
func (m *NoAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoAuth.Merge(m, src)
}
func (m *NoAuth) XXX_Size() int {
	return xxx_messageInfo_NoAuth.Size(m)
}
func (m *NoAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_NoAuth.DiscardUnknown(m)
}

var xxx_messageInfo_NoAuth proto.InternalMessageInfo

func (m *NoAuth) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NoAuth) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *NoAuth) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Auth)(nil), "fileserv.Auth")
	proto.RegisterType((*NoAuth)(nil), "fileserv.noAuth")
	proto.RegisterType((*Response)(nil), "fileserv.Response")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0xa9, 0x69, 0x3a, 0x8a, 0x86, 0x45, 0x24, 0xe8, 0xa5, 0xe4, 0xd4, 0xd3, 0x22,
	0x8a, 0xe0, 0xd5, 0x7a, 0x50, 0x14, 0x24, 0x44, 0xd0, 0x9b, 0xb0, 0x69, 0xc6, 0x36, 0xb8, 0xc9,
	0xc4, 0xdd, 0x4d, 0xb5, 0xfe, 0x7a, 0xd9, 0xa4, 0x4b, 0x15, 0x3c, 0x7a, 0x7b, 0xdf, 0xf2, 0x66,
	0xde, 0xce, 0x0c, 0x84, 0x45, 0xce, 0x1b, 0x45, 0x86, 0x58, 0xf8, 0x5a, 0x4a, 0xd4, 0xa8, 0x96,
	0xc9, 0x0b, 0x0c, 0xae, 0x5a, 0xb3, 0x60, 0x31, 0x0c, 0x53, 0xb1, 0x92, 0x24, 0x8a, 0xd8, 0x1b,
	0x7b, 0x93, 0xbd, 0xcc, 0x21, 0x3b, 0x84, 0x9d, 0x1b, 0x45, 0x6d, 0x13, 0x6f, 0x8f, 0xbd, 0xc9,
	0x28, 0xeb, 0x81, 0x45, 0xe0, 0xdf, 0xe3, 0x2a, 0xf6, 0xbb, 0x37, 0x2b, 0xad, 0xcf, 0xd0, 0x1b,
	0xd6, 0xf1, 0xa0, 0xf7, 0x75, 0x90, 0xdc, 0x41, 0x50, 0xd3, 0xff, 0x24, 0x24, 0x4f, 0x10, 0x66,
	0xa8, 0x1b, 0xaa, 0x35, 0xb2, 0x23, 0x08, 0x14, 0xea, 0x56, 0x9a, 0xae, 0xd9, 0x28, 0x5b, 0x93,
	0x4d, 0xa9, 0x50, 0x6b, 0x31, 0xc7, 0x75, 0x37, 0x87, 0x3f, 0xf3, 0xfd, 0x5f, 0xf9, 0x67, 0x5f,
	0x30, 0x7c, 0x44, 0xb5, 0x2c, 0x67, 0xc8, 0x2e, 0x21, 0xca, 0x15, 0x89, 0xe2, 0x5a, 0x68, 0x93,
	0xe1, 0x7b, 0x8b, 0xda, 0xb0, 0x7d, 0xee, 0xb6, 0xc5, 0xed, 0x20, 0xc7, 0x6c, 0xc3, 0xee, 0x3b,
	0xc9, 0x16, 0xbb, 0x80, 0xdd, 0x07, 0x52, 0x95, 0x2b, 0x8a, 0x36, 0xa6, 0x7e, 0xfe, 0xbf, 0xcb,
	0xa6, 0xa7, 0x70, 0x52, 0x12, 0x9f, 0xab, 0x66, 0xc6, 0xf1, 0x53, 0x54, 0x8d, 0x44, 0xcd, 0x17,
	0x28, 0x25, 0x7d, 0x90, 0x92, 0xc5, 0xf4, 0xe0, 0xd6, 0xea, 0x67, 0xab, 0x53, 0x7b, 0xb9, 0xd4,
	0xcb, 0x83, 0xee, 0x84, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x8c, 0xa6, 0xb9, 0xce,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	BroadCastRequest(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Response, error)
	NormRequest(ctx context.Context, in *NoAuth, opts ...grpc.CallOption) (*Response, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) BroadCastRequest(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/fileserv.Service/broadCastRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) NormRequest(ctx context.Context, in *NoAuth, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/fileserv.Service/NormRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	BroadCastRequest(context.Context, *Auth) (*Response, error)
	NormRequest(context.Context, *NoAuth) (*Response, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) BroadCastRequest(ctx context.Context, req *Auth) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadCastRequest not implemented")
}
func (*UnimplementedServiceServer) NormRequest(ctx context.Context, req *NoAuth) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NormRequest not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_BroadCastRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).BroadCastRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileserv.Service/BroadCastRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).BroadCastRequest(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_NormRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NormRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileserv.Service/NormRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NormRequest(ctx, req.(*NoAuth))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fileserv.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "broadCastRequest",
			Handler:    _Service_BroadCastRequest_Handler,
		},
		{
			MethodName: "NormRequest",
			Handler:    _Service_NormRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
